const habits=[{id:'reading',name:'読書',plant:'coffeetree'},{id:'exercise',name:'運動',plant:'hawortia'},{id:'python',name:'Python',plant:'jewelorchid'}];
const MAX_GROWTH_DAYS=30,storeKey='habit-garden-v1';
const PLANT_IMAGES={coffeetree:['images/coffeetree-1.png','images/coffeetree-2.png','images/coffeetree-3.png','images/coffeetree-4.png','images/coffeetree-5.png'],hawortia:['images/hawortia-1.png','images/hawortia-2.png','images/hawortia-3.png','images/hawortia-4.png','images/hawortia-5.png'],jewelorchid:['images/jewelorchid-1.png','images/jewelorchid-2.png','images/jewelorchid-3.png','images/jewelorchid-4.png','images/jewelorchid-5.png']};
const state=loadState();rotateMonthIfNeeded(state);saveState();
const habitList=document.getElementById('habitList'),calendarTitle=document.getElementById('calendarTitle'),calendarGrid=document.getElementById('calendarGrid'),calendarDetail=document.getElementById('calendarDetail'),shelfList=document.getElementById('shelfList'),template=document.getElementById('habitCardTemplate');
let selectedDayKey=getDayKey(new Date());render();
function render(){renderHabits();renderCalendar();renderShelf()}
function renderHabits(){const now=new Date(),nowKey=getDayKey(now),monthKey=getMonthKey(now);habitList.innerHTML='';habits.forEach(h=>{const monthData=state.current[monthKey]??(state.current[monthKey]={}),days=monthData[h.id]??(monthData[h.id]=[]),givenToday=days.includes(nowKey),node=template.content.firstElementChild.cloneNode(true);node.querySelector('.habit-name').textContent=h.name;setPlantImage(node.querySelector('.plant'),h,days.length);node.querySelector('.status').textContent=givenToday?'今日の記録は完了しました。':'今日はまだ記録していません。';const btn=node.querySelector('.energy-btn');btn.disabled=givenToday;if(givenToday)btn.textContent='今日の分は記録済み';btn.addEventListener('click',()=>{days.push(nowKey);selectedDayKey=nowKey;saveState();const sparkles=node.querySelector('.sparkles'),plant=node.querySelector('.plant');sparkles.classList.remove('show');void sparkles.offsetWidth;sparkles.classList.add('show');plant.classList.add('bounce');setTimeout(()=>plant.classList.remove('bounce'),420);setTimeout(render,500)});habitList.appendChild(node)})}
function renderCalendar(){const now=new Date(),monthKey=getMonthKey(now),[year,month]=monthKey.split('-').map(Number),firstDay=new Date(year,month-1,1),lastDay=new Date(year,month,0),monthData=state.current[monthKey]||{},todayKey=getDayKey(now);calendarTitle.textContent=`${year}年${month}月`;calendarGrid.innerHTML='';for(let i=0;i<firstDay.getDay();i++){const blank=document.createElement('div');blank.className='calendar-day blank';calendarGrid.appendChild(blank)}for(let day=1;day<=lastDay.getDate();day++){const dayKey=formatLocalDate(new Date(year,month-1,day)),completedHabits=habits.filter(h=>(monthData[h.id]||[]).includes(dayKey)),cell=document.createElement('article');cell.className='calendar-day';if(dayKey===todayKey)cell.classList.add('today');if(dayKey===selectedDayKey)cell.classList.add('selected');cell.tabIndex=0;cell.setAttribute('aria-label',`${month}月${day}日 ${completedHabits.length}件記録`);cell.innerHTML=`<div class="calendar-date">${day}</div><div class="calendar-marks"></div>`;const marks=cell.querySelector('.calendar-marks');completedHabits.forEach(h=>{const mark=document.createElement('span');mark.className=`calendar-mark ${h.id}`;mark.title=h.name;marks.appendChild(mark)});cell.addEventListener('click',()=>selectCalendarDay(dayKey));cell.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectCalendarDay(dayKey)}});calendarGrid.appendChild(cell)}renderCalendarDetail(monthKey)}
function selectCalendarDay(dayKey){selectedDayKey=dayKey;renderCalendar()}
function renderCalendarDetail(monthKey){const monthData=state.current[monthKey]||{},selectedDate=parseDayKey(selectedDayKey),completedCount=habits.filter(h=>(monthData[h.id]||[]).includes(selectedDayKey)).length;calendarDetail.innerHTML='';const title=document.createElement('h3');title.textContent=`${selectedDate.getMonth()+1}月${selectedDate.getDate()}日の記録`;calendarDetail.appendChild(title);const summary=document.createElement('p');summary.className='calendar-summary';summary.textContent=`${completedCount}/${habits.length} 件完了`;calendarDetail.appendChild(summary);const list=document.createElement('ul');list.className='calendar-detail-list';habits.forEach(h=>{const done=(monthData[h.id]||[]).includes(selectedDayKey),item=document.createElement('li');item.className=done?'done':'missed';item.innerHTML=`<span>${h.name}</span><strong aria-label="${done?'完了':'未実行'}">${done?'🌱':'-'}</strong>`;list.appendChild(item)});calendarDetail.appendChild(list)}
function renderShelf(){shelfList.innerHTML='';habits.forEach(h=>{const block=document.createElement('section');block.className='shelf-block';block.innerHTML=`<h3>${h.name}</h3>`;const row=document.createElement('div');row.className='shelf-row';const entries=Object.entries(state.archive[h.id]||{}).sort((a,b)=>b[0].localeCompare(a[0]));if(!entries.length){row.innerHTML='<p class="status">まだ棚に植物はありません。</p>'}else entries.forEach(([month,count])=>{const item=document.createElement('div'),plant=document.createElement('img'),date=document.createElement('div');item.className='shelf-item';plant.className='shelf-plant';plant.src=getPlantImage(h.plant,count);plant.alt=`${h.name} ${month} の最終形態`;date.className='shelf-date';date.textContent=month;item.appendChild(plant);item.appendChild(date);row.appendChild(item)});block.appendChild(row);shelfList.appendChild(block)})}
function setPlantImage(image,habit,completedDays){image.src=getPlantImage(habit.plant,completedDays);image.alt=`${habit.name} ${completedDays}/${MAX_GROWTH_DAYS}日`}
function getPlantImage(plant,completedDays){return PLANT_IMAGES[plant][getGrowthStage(completedDays)]}
function getGrowthStage(completedDays){if(completedDays>=MAX_GROWTH_DAYS)return 4;if(completedDays>=22)return 3;if(completedDays>=15)return 2;if(completedDays>=8)return 1;return 0}
function getDayKey(date){const local=new Date(date);if(local.getHours()<6)local.setDate(local.getDate()-1);return formatLocalDate(local)}
function getMonthKey(date){const local=new Date(date);if(local.getHours()<6)local.setDate(local.getDate()-1);return formatLocalMonth(local)}
function formatLocalDate(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function formatLocalMonth(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function parseDayKey(dayKey){const [year,month,day]=dayKey.split('-').map(Number);return new Date(year,month-1,day)}
function rotateMonthIfNeeded(targetState){const monthKey=getMonthKey(new Date());for(const key of Object.keys(targetState.current)){if(key!==monthKey){habits.forEach(h=>{const count=(targetState.current[key][h.id]||[]).length;targetState.archive[h.id]=targetState.archive[h.id]||{};targetState.archive[h.id][key]=count});delete targetState.current[key]}}}
function loadState(){const parsed=JSON.parse(localStorage.getItem(storeKey)||'{}');return{current:{},archive:{},...parsed}}
function saveState(){rotateMonthIfNeeded(state);localStorage.setItem(storeKey,JSON.stringify(state))}
document.querySelectorAll('.nav-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const screen=btn.dataset.screen;document.getElementById('homeScreen').classList.toggle('active',screen==='home');document.getElementById('calendarScreen').classList.toggle('active',screen==='calendar');document.getElementById('shelfScreen').classList.toggle('active',screen==='shelf')})});
